config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: :registrations }
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  get "/about", to: "pages#about"
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  post 'mail/send', to: "pages#sendmail"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contacts, only: %i[new create]
  resources :stations do
    resources :reviews, only: %i[index new create destroy]
  end
end

app/models/station.rb
class Station < ApplicationRecord
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :station_chargers, dependent: :destroy
  has_many :chargers, through: :station_chargers
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[ show edit update destroy ]

  # GET /stations or /stations.json
  def index
    @stations = Station.all
    @markers = @stations.geocoded.map do |station|
      {
        lat: station.latitude,
        lng: station.longitude,
        info_window: render_to_string(partial: "info_window", locals: { station: station }),
        station_id: station.id,
        image_url:  station.chargers.pluck(:ctype).include?("CHADEMO") || station.chargers.pluck(:ctype).include?("CCS") ?
          helpers.asset_url("fast-marker.svg") :
          helpers.asset_url("marker.svg")
      }
    end
  end

  # GET /stations/1 or /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
    @charger = Charger.new
    @chargers = Charger.all
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations or /stations.json
  def create
    @station = Station.new(station_params)
    @station.user = current_user
    respond_to do |format|
      if @station.save
        chargers = params["charger"]
        charger_count = params["charger_count"]
        chargers.each_with_index do |charger_id, index|
          @station_charger = StationCharger.new
          @station_charger.station = @station
          @station_charger.charger_id = charger_id
          @station_charger.charger_count = charger_count[index]
          @station_charger.save
        end
        format.html { redirect_to stations_path, notice: "Station was successfully created." }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1 or /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to station_url(@station), notice: "Station was successfully updated." }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1 or /stations/1.json
  def destroy
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url, notice: "Station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:name, :address, :user_id, :review_id, :photo)
    end
    def charger_params
      params.require(:charger).permit(:charger_id)
    end
end

app/views/stations/_form.html.erb
  <div class="container p-3" >
    <%= simple_form_for(@station) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">

        <%= f.input :name, label: false,
                      required: true,
                      # autofocus: true,
                      input_html: { autocomplete: "Name", placeholder:"Name", class:"mt-3"} %>
        <%= f.input :address, label: false,
                      required: true,
                      # autofocus: true,
                      input_html: { autocomplete: "Address", placeholder:"Address", class:"mt-3"}  %>
        <%= f.input :photo, as: :file,
                      label: false,
                      required: true,
                      # autofocus: true,
                      input_html: { placeholder:"Photo", class:"mt-3"}  %>
<br>
        <div data-controller="insert-in-form">
          <div data-insert-in-form-target="outerform">
            <div class="form-row mt-3" data-insert-in-form-target="form">
              <select name="charger[]" class="btn btn-primary dropdown-toggle col-7">
                <%= Charger.all.each do |charger| %>
                <li style="list-style: none">
                  <option value="<%=charger.id%>"><%= charger.ctype %> - <%= charger.capacity %>kW
                  <% if charger.tethered? && charger.ctype == "Type 2" %>
                       - Tethered
                  <% end %>
                  </option>
                  <% end %>
              </select>
                x <input data-insert-in-form-target="count" class="form-group col-2" type="number" id="charger_count" name="charger_count[]" default="1" placeholder="1" min="1" step="1">
            </div>

          </div>
          <div class="form-actions text-center mt-3" data-insert-in-form-target="button">

            <a href="" data-action="click->insert-in-form#add">Add charger</a>
          </div>
        </div>

<br>
      <div class="form-actions text-center" >
        <%= f.button :submit, "Submit", class:"btn btn-primary w-50 m-3 rounded-pill" %>
      </div>




    <% end %>

  </div>

app/views/stations/_info_window.html.erb
<span id="drawer"></span>
<div class="container  mt-2">
  <div class="offcanvas-header">
    <h5 class="m-2"><b><%= station.name.capitalize %></b></h5>

    <button type="button" class="btn btn-primary rounded-pill go" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sign-turn-right-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M9.05.435c-.58-.58-1.52-.58-2.1 0L.436 6.95c-.58.58-.58 1.519 0 2.098l6.516 6.516c.58.58 1.519.58 2.098 0l6.516-6.516c.58-.58.58-1.519 0-2.098L9.05.435ZM9 8.466V7H7.5A1.5 1.5 0 0 0 6 8.5V11H5V8.5A2.5 2.5 0 0 1 7.5 6H9V4.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L9.41 8.658A.25.25 0 0 1 9 8.466Z"></path>
      </svg>
        Go
    </button>



    <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasBottomLabel">Navigate</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
    <div class="offcanvas-body small">






    <div style="margin: 0 auto; display: block; text-align: center; rounded ">
      <a href="http://maps.apple.com/maps?q=<%=station.latitude%>,<%=station.longitude%>"><img src="https://www.apple.com/v/maps/d/images/overview/intro_icon__dfyvjc1ohbcm_large.png" width="75" height="75"
      alt="" style="margin: 8px;"></a>


      <a href="https://www.google.com/maps/place/<%=station.latitude%>,<%=station.longitude%>"><img src="https://i0.wp.com/originalapk.com/wp-content/uploads/2019/12/Google-Maps-Icon-Original-APK.png?fit=300%2C300&ssl=1" width="75" height="75" alt=""></a>

      <a href="https://waze.com/ul?q=<%=station.latitude%>,<%=station.longitude%>"><img src="https://www.digital-make-it.com/uploaded/136550/waze11-modifier-9343789100488398.png" width="80" height="80" alt=""></a>

    </div>


    </div>


      </div>
    </div>



    <%# <span class="badge bg-primary">Available</span> %>
  </div>
    <% if !station.reviews.empty? %>
      <% note = 0 %>
      <% station.reviews.each do |review| %>
        <% note += review.rating  %>
      <% end %>
      <% average = note.fdiv((station.reviews).size) %>
    <% end %>
    <% if !average.nil? %>
      <h6 style="margin-left: 19px"><% average.to_i.times do  %>
            <i class='fa-sharp fa-solid fa-star' style="color: #ffcd3c;"></i>
          <% end %>
          <% (5 - average.to_i).times do %>
            <i class='fa-regular fa-star' style="color: #ffcd3c;"></i>
          <% end %>
          (<%= (station.reviews).size %>)
      </h6>
    <% end %>
  </div>
<p><%= station.address %></p>
  <% if station.photo.key.nil? %>
    <%= image_tag "https://doc-04-a4-mymaps.googleusercontent.com/untrusted/hostedimage/sm8qmc4gucqmtv2n8d3g746lsc/k58foeocjlvtgok8gtgveloeog/1662900235750/JHdNRxuCceXe4dzVnCmOKym7Qn5qjH34/12207485209966916948/5AFzc1vZ2vMQfAZFnbBibNGHCpCAS9gYIa1Hz-620ep9aT2bOwfg5bDiSFx2kJZksOMuEuz7bXJwlq91rTByG1DvdXHZSteYJKUJ-vi8hDsiOK7ucU9TznD56N6s8P1Dme5F9-9et7t9vxh_3fvNwIHvEELyx7f2SHVoKzoQGbQFCLV8lKsSAKaU8aOkrjrVw45T9Rkw?session=0&fife=s16383", height: 200, width: 350, crop: :fill %>
  <% else %>
    <%= cl_image_tag station.photo.key, height: 200, width: 350,crop: :fill, class: "mb-4" %>
  <% end %>
<div class="d-flex justify-content-around align-items-center text-center">
    <% station.station_chargers.each do |station_charger| %>
      <li style="list-style: none">
        <div class="column m-auto" style="height: 45px;">
          <%= image_tag(station_charger.charger.ctype+".svg", style:"width:35px; height:35px")%>
        </div>
        <div style="height: 45px; ">
          <h6><span style="display: inline-block; min-width: 66px; font-size: 14px">
          <b><%= station_charger.charger.ctype%></b></span>
          <li style="font-size: 14px">
            <% if station_charger.charger.tethered? && station_charger.charger.ctype == "Type 2" %>
              Tethered
            <% end %>
          </li>
          <li style="font-size: 14px">
          <% if station_charger.charger.capacity % 1 == 0 %>
              <%= station_charger.charger.capacity.to_i %> kW x
            <% else %>
              <%= station_charger.charger.capacity %> kW x
          <% end %>
          <%= station_charger.charger_count %></li></h6>
        </div>
          </li>
    <% end %>
    </div>
    <hr>
</div>
      <div class="text-center">
    <%= link_to "Leave a review", new_station_review_path(station)%>
<br>
    <br>
  <button class="btn btn-primary rounded-pill" id="showReviews" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    See reviews
  </button>
  <script>
  </script>
  </div>
<br>
<br>
<div class="collapse" id="collapseExample">
  <div class="card-body">
   <% if !station.reviews.empty? %>
  <% station.reviews.each do |review| %>


    <i class="fas fa-quote-left pe-2"></i><%= review.content %></i>
    <ul class="list-unstyled d-flex justify-content text-warning mb-0">
        <% review.rating.to_i.times do %>
          <li><i class="fas fa-star fa-sm"></i></li>
        <% end %>
        <% (5 - review.rating).to_i.times do %>
          <li><i class="far fa-star fa-sm"></i></li>
        <% end %>
      </ul>
    <%# <p class="mb-0"><b>Rating:</b><%= review.rating %>
    <% if review.photo.key? %>
      <%= cl_image_tag review.photo.key, height: 50, width: 50, crop: :fill %>
    <% end %>
    <hr>
  <% end %>
<% end %>
 </div>
</div>

</div>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>

app/views/stations/_station.html.erb
<div id="<%= dom_id station %>">
  <p>
    <strong>Name:</strong>
    <%= station.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= station.address %>
  </p>

  <p>
    <strong>User:</strong>
    <%= station.user_id %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= station.review_id %>
  </p>

</div>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render "form", station: @station %>

<br>

<div>
  <%= link_to "Show this station", @station %> |
  <%= link_to "Back to stations", stations_path %>
</div>

app/views/stations/index.html.erb
<div style="width: 100%; height: 100vh;"
  class="mymap col-xs-12"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"

  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>


<div class="d-none" style="top: 500px;" id="popup"></div>

<div class="support">
	<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-info-circle-fill" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom"viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
  </svg></div>
  <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasBottomLabel">map legend</h5>
    </div>
    <div class="offcanvas-body small text-center">
      <img src="https://i.ibb.co/cXkwb6w/Ajouter-un-titre-3.png" width="250px" height="150px" alt="">
    </div>
  </div>
</div>

 <%= render "shared/navbar" %>

app/views/stations/new.html.erb
<div class="container text-center p-4">
  <div class="offcanvas-header">
    <h5 id="offcanvasRightLabel">Add a new station</h5>
    <a href="/stations"><button type="button" class="btn-close text-reset" aria-label="Close"></button></a>
  </div>
<img src="https://i.ibb.co/Zzrx6V8/728-generated.jpg"  alt="EV-212" width="280px" height="280px"></a>
  <%= render "form", station: @station %>
</div>

app/views/stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @station %>

<div>
  <%= link_to "Edit this station", edit_station_path(@station) %> |
  <%= link_to "Back to stations", stations_path %>

  <%= button_to "Destroy this station", @station, method: :delete %>
</div>