config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: :registrations }
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  get "/about", to: "pages#about"
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  post 'mail/send', to: "pages#sendmail"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :contacts, only: %i[new create]
  resources :stations do
    resources :reviews, only: %i[index new create destroy]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="fixed-top alert alert-primary alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="fixed-top alert alert-primary alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="main-wrapper">


  <input type="checkbox" name="open" id="open">

  <div class="navbar-lewagon">
    <div class="icon-wrapper">
      <div>
        <a  href="/stations"><i class="fa-solid fa-map-location-dot"></i></a>
      </div>
      <div id="open-nav">
        <label for="open"> <i class="fa-solid fa-bars"></i></label>
      </div>
      <div>
        <a href="<%= new_station_path %>"><i class="fa-solid fa-plus" ></i></a>
      </div>
      <div>
        <a href="/profile"><i class="fa-solid fa-user"></i></a>
      </div>
    </div>
  </div>

</div>